spring.application.name=springboot-ai

# Gemini Key
spring.ai.model.chat=google-genai
spring.ai.google.genai.api-key=${GEMINI_API_KEY}

# 增加非同步的延遲時間
spring.mvc.async.request-timeout=120000

# 確保串流不被壓縮 (預設通常是 false，但建議明確關閉)
server.compression.enabled=false